// Lista de palabras comunes del español para el modo "palabra al azar".
// Sin nombres propios, solo vocabulario general.
export const words = [
  'casa', 'perro', 'gato', 'agua', 'fuego', 'tierra', 'aire', 'sol', 'luna', 'estrella',
  'cielo', 'nube', 'lluvia', 'viento', 'monte', 'río', 'mar', 'playa', 'arena', 'piedra',
  'árbol', 'flor', 'hoja', 'fruta', 'semilla', 'raíz', 'bosque', 'jardín', 'campo', 'huerta',
  'pan', 'leche', 'queso', 'huevo', 'carne', 'pescado', 'arroz', 'sopa', 'sal', 'azúcar',
  'aceite', 'naranja', 'manzana', 'plátano', 'limón', 'uva', 'pera', 'sandía', 'melón', 'cereza',
  'mesa', 'silla', 'cama', 'puerta', 'ventana', 'techo', 'pared', 'suelo', 'escalera', 'llave',
  'libro', 'lápiz', 'papel', 'cuaderno', 'mochila', 'reloj', 'espejo', 'lámpara', 'cortina', 'alfombra',
  'camisa', 'pantalón', 'zapato', 'sombrero', 'abrigo', 'bufanda', 'guante', 'cinturón', 'bolsillo', 'botón',
  'cabeza', 'cara', 'ojo', 'nariz', 'boca', 'oreja', 'diente', 'lengua', 'cuello', 'hombro',
  'brazo', 'mano', 'dedo', 'pierna', 'pie', 'rodilla', 'espalda', 'pecho', 'corazón', 'estómago',
  'padre', 'madre', 'hijo', 'hija', 'hermano', 'hermana', 'abuelo', 'abuela', 'tío', 'tía',
  'primo', 'prima', 'amigo', 'amiga', 'vecino', 'vecina', 'maestro', 'alumno', 'médico', 'enfermero',
  'ciudad', 'pueblo', 'calle', 'plaza', 'parque', 'tienda', 'mercado', 'hospital', 'escuela', 'iglesia',
  'coche', 'autobús', 'tren', 'barco', 'avión', 'bicicleta', 'moto', 'camino', 'puente', 'esquina',
  'trabajo', 'oficina', 'fábrica', 'dinero', 'moneda', 'billete', 'cuenta', 'precio', 'compra', 'venta',
  'tiempo', 'hora', 'minuto', 'segundo', 'día', 'noche', 'mañana', 'tarde', 'semana', 'mes',
  'año', 'invierno', 'verano', 'otoño', 'primavera', 'fiesta', 'juego', 'música', 'baile', 'canción',
  'pelota', 'juguete', 'muñeca', 'cometa', 'columpio', 'piscina', 'costa', 'montaña', 'valle', 'desierto',
  'pájaro', 'pez', 'caballo', 'vaca', 'oveja', 'cerdo', 'gallina', 'pato',
  'conejo', 'ratón', 'oso', 'lobo', 'zorro', 'tigre', 'león', 'elefante', 'mono', 'serpiente',
  'grande', 'pequeño', 'alto', 'bajo', 'largo', 'corto', 'ancho', 'estrecho', 'nuevo', 'viejo',
  'rápido', 'lento', 'caliente', 'frío', 'limpio', 'sucio', 'fuerte', 'débil', 'fácil', 'difícil',
  'feliz', 'triste', 'contento', 'cansado', 'dormido', 'despierto', 'hambriento', 'lleno', 'vacío', 'abierto',
  'cerrado', 'claro', 'oscuro', 'suave', 'duro', 'dulce', 'amargo', 'salado', 'seco', 'mojado',
  'hablar', 'escuchar', 'mirar', 'leer', 'escribir', 'correr', 'saltar', 'nadar', 'volar', 'caminar',
  'comer', 'beber', 'dormir', 'jugar', 'estudiar', 'trabajar', 'comprar', 'vender', 'abrir', 'cerrar',
  'entrar', 'salir', 'subir', 'bajar', 'llegar', 'partir', 'buscar', 'encontrar', 'perder', 'ganar',
  'amor', 'paz', 'guerra', 'libertad', 'verdad', 'mentira', 'sueño', 'idea', 'palabra', 'nombre',
];
